### PR TITLE
a demo of branching and checkout

### PR DESCRIPTION
**Pull request by catherine-leung**

### CODE REVIEW

**Comment by JoelKenne** [comment]
I DONT LIKE IT

**Comment by AnirudhaNandi** [comment]
The gap is a waste of server space

**Comment by catherine-leung** [comment]
why not?

**Comment by JoelKenne** [comment]
You just added a space

**Comment by AKMDM** [comment]
There's no need to add the extra space.

**Comment by catherine-leung** [comment]
fine, its removed

**Comment by JoelKenne** [comment]
Gg!

**Comment by AKMDM** [comment]
That's better.

**Comment by JoelKenne** [comment]
Thank you for introducing us to github. :)

**Pull request merged**
